import React, { useEffect } from 'react';
import { motion } from 'motion/react';
import { Info, Loader2, CheckCircle2, Library } from 'lucide-react';
import { AIBadge } from './ai';
import type { GrowthReport } from '../types';

export type GrowthReportModalProps = {
  open: boolean;
  onClose: () => void;
  title: string;
  /** Optional; hidden by default for a cleaner UI */
  applicationId?: number | null;
  showApplicationId?: boolean;
  loading: boolean;
  error: string;
  data: GrowthReport | null;
  dismissLabel?: string;
};

export function GrowthReportModal({
  open,
  onClose,
  title,
  applicationId,
  showApplicationId = false,
  loading,
  error,
  data,
  dismissLabel = 'Got it, thanks!',
}: GrowthReportModalProps) {
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, onClose]);

  if (!open) return null;

  const gaps = data?.skill_gaps ?? [];
  const recs = data?.recommendations ?? [];
  const resources = data?.suggested_resources ?? [];

  return (
    <div
      className="fixed inset-0 z-50 overflow-y-auto bg-black/45 backdrop-blur-sm"
      role="dialog"
      aria-modal="true"
      aria-labelledby="growth-report-modal-title"
    >
      <div
        className="flex min-h-full items-center justify-center p-4 sm:p-8"
        onClick={onClose}
      >
        <motion.div
          initial={{ opacity: 0, y: 10, scale: 0.98 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          transition={{ duration: 0.2 }}
          className="my-6 w-full max-w-6xl rounded-3xl border border-gray-100 bg-white p-6 shadow-2xl sm:my-10 sm:p-10"
          onClick={(e) => e.stopPropagation()}
        >
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="min-w-0">
            <h2 id="growth-report-modal-title" className="text-xl font-bold leading-tight">
              <span className="ai-text-gradient">{title}</span>
            </h2>
            {showApplicationId && applicationId != null && (
              <p className="mt-1 text-[11px] font-medium uppercase tracking-wide text-gray-400">
                Application #{applicationId}
              </p>
            )}
          </div>
          <AIBadge />
        </div>

        {loading && (
          <div className="flex flex-col items-center justify-center gap-3 py-14 text-gray-500">
            <Loader2 className="animate-spin" size={32} aria-hidden />
            <p className="text-sm font-medium">Preparing your report…</p>
          </div>
        )}

        {!loading && error && (
          <div className="mt-5 rounded-2xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-800">
            {error}
          </div>
        )}

        {!loading && !error && data && (
          <div className="mt-5 space-y-8">
            <div className="growth-report-ai-notice flex gap-4 rounded-2xl p-4 sm:p-5">
              <div
                className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border text-[color:var(--color-ai-cyan)] sm:h-11 sm:w-11"
                style={{
                  backgroundColor: 'color-mix(in srgb, var(--color-ai-cyan) 14%, white)',
                  borderColor: 'color-mix(in srgb, var(--color-ai-cyan) 35%, white)',
                }}
                aria-hidden
              >
                <Info size={20} strokeWidth={2.25} />
              </div>
              <p className="text-sm leading-relaxed text-gray-700 sm:text-[15px] sm:leading-relaxed">
                This report is generated by our AI from your CV analysis and the job requirements.
                Use these insights to improve your profile for future applications.
              </p>
            </div>

            <div className="grid gap-10 lg:grid-cols-2 lg:gap-x-14 lg:gap-y-0">
              <div className="space-y-10 min-w-0">
                {gaps.length > 0 && (
                  <section>
                    <h3 className="mb-3 flex items-center gap-2 text-[11px] font-black uppercase tracking-[0.12em] text-brand-black">
                      <span className="h-2 w-2 shrink-0 rounded-full bg-rose-500" aria-hidden />
                      Skill gaps
                    </h3>
                    <div className="flex flex-wrap gap-2">
                      {gaps.map((label, i) => (
                        <span
                          key={`${label}-${i}`}
                          className="inline-flex rounded-full bg-rose-50 px-3 py-1.5 text-xs font-semibold text-rose-900 ring-1 ring-rose-100/90 sm:text-sm"
                        >
                          {label}
                        </span>
                      ))}
                    </div>
                  </section>
                )}

                {resources.length > 0 && (
                  <section>
                    <h3 className="mb-3 flex items-center gap-2 text-[11px] font-black uppercase tracking-[0.12em] text-brand-black">
                      <span
                        className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full"
                        style={{
                          backgroundColor: 'color-mix(in srgb, var(--color-ai-cyan) 14%, white)',
                          color: 'var(--color-ai-cyan)',
                        }}
                        aria-hidden
                      >
                        <Library size={12} strokeWidth={2.5} />
                      </span>
                      Suggested resources
                    </h3>
                    <ul className="space-y-2.5 border-l-2 border-cyan-100 pl-4">
                      {resources.map((line, i) => (
                        <li key={`${line}-${i}`} className="text-sm leading-relaxed text-gray-600 sm:text-[15px]">
                          {line}
                        </li>
                      ))}
                    </ul>
                  </section>
                )}
              </div>

              {recs.length > 0 && (
                <section className="min-w-0">
                  <h3 className="mb-3 flex items-center gap-2 text-[11px] font-black uppercase tracking-[0.12em] text-brand-black">
                    <span
                      className="h-2 w-2 shrink-0 rounded-full bg-[color:var(--color-ai-cyan)]"
                      aria-hidden
                    />
                    Recommendations
                  </h3>
                  <ul className="space-y-3 sm:space-y-3.5">
                    {recs.map((line, i) => (
                      <li key={`${line}-${i}`} className="flex gap-3 text-sm text-gray-700 sm:text-[15px]">
                        <span
                          className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full"
                          style={{
                            backgroundColor: 'color-mix(in srgb, var(--color-ai-cyan) 18%, white)',
                            color: 'var(--color-ai-cyan)',
                          }}
                          aria-hidden
                        >
                          <CheckCircle2 size={14} strokeWidth={2.5} />
                        </span>
                        <span className="leading-relaxed pt-0.5">{line}</span>
                      </li>
                    ))}
                  </ul>
                </section>
              )}
            </div>
          </div>
        )}

        <button
          type="button"
          onClick={onClose}
          disabled={loading}
          className="mt-8 w-full rounded-full py-3.5 text-sm font-bold text-white shadow-md transition hover:opacity-95 active:scale-[0.99] disabled:cursor-not-allowed disabled:opacity-60 sm:mt-10 lg:max-w-md lg:mx-auto"
          style={{ backgroundColor: 'var(--color-ai-cyan)' }}
        >
          {loading ? 'Please wait…' : dismissLabel}
        </button>
        </motion.div>
      </div>
    </div>
  );
}
